client:
  b:
    baseUrl: "http://localhost:8081/api"
  gismeteo:
    baseUrl: "https://api.gismeteo.net/v2/weather/current"
    token: "56b30cb255.3443075"
  openweather:
    baseUrl: "https://api.openweathermap.org/data/3.0/onecall"
    appId: "token"
